### ISSUE TITLE
Default List

### ISSUE THREAD

**Issue by jodavis16** [squeek502/CreativeBlocks#12]
I have an issue with the default list. It is always in effect. I wrote up my own list and still the default list was in effect with my list. I tried changing the name of my file to default but the mod just rewrote the default one.

**Comment by squeek502** [comment]
The mod will load _all_ .json files in its config folder, so if you have both your custom .json and the default.json, both will be used. If you only want your custom config to be loaded, you need to delete default.json.

So, try deleting `default.json` and naming your file something other than `default.json` (e.g. `custom.json`).

**Comment by jodavis16** [comment]
Thanks so much for your help. This did the trick and is working just fine now.

Date: Wed, 2 Mar 2016 11:28:46 -0800
