### ISSUE TITLE
CreativeBlocks not generating the Default.json

### ISSUE THREAD

**Issue by Excaerious** [squeek502/CreativeBlocks#5]
![image](https://cloud.githubusercontent.com/assets/6412128/6033204/c687fddc-abe0-11e4-8072-b50e743d2869.png)

I know it is a pre-release, but I just wanted to bring it to your attention that it's quite simply not generating the config for me at all. Re-installed a few times too, but it just won't generate it.

**Comment by squeek502** [comment]
Could you upload a log from when you launch Minecraft with the mod installed? It should print an error if it fails to create the default config.

You can get the default config here until this gets fixed: https://raw.githubusercontent.com/squeek502/CreativeBlocks/master/resources/config/default.json

**Comment by Excaerious** [comment]
https://gist.githubusercontent.com/Excaerious/13ae8d604f87edef2804/raw/Error,%20CreativeBlocks

There is my start-up log all the way until the startup screen. It doesn't seem like it's actually throwing the error. Let me know if you need me to do any other tests for you (e.g. removing a mod temporarily). 

Also, thanks for the quick response.

Quick Edit: With the json is works perfectly under the guidelines you've given. Managed to add all of Ztones blocks to the whitelist and now they all work creatively. Thanks a lot for the mod.

**Comment by squeek502** [comment]
Try using this build and see if it fixes it: [CreativeBlocks-mc1.7.10-0.1.0-verbose.jar](http://www.ryanliptak.com/misc/CreativeBlocks-mc1.7.10-0.1.0-verbose.jar)

If not, post the log you get when running it.

**Comment by squeek502** [comment]
Uh, wow I'm a doof.

The file is being written to config/default.json instead of config/CreativeBlocks/default.json... Will fix and upload a new build. Thanks for reporting it, not sure how I didn't notice while testing it.

**Comment by squeek502** [comment]
Should be fixed in v0.1.1: https://github.com/squeek502/CreativeBlocks/releases/latest
