### ISSUE TITLE
[feature request] Allow blocks to NOT be destroyed in one hit.

### ISSUE THREAD

**Issue by nephatrine** [squeek502/CreativeBlocks#9]
It's super annoying to have to keep running around fixing my base since I'm so clumsy and keep bashing holes into walls and floors. Just removing a machine or other block in a room made of creative blocks can be very tense as one has to be super careful not to destroy the block behind/under it - and fighting is definitely a no around them. I wanted creative blocks so I could build mighty towers and castles... but when they all feel like paper mache it kinda spoils the fun. Without the ability to use the mouse wheel to pull up a copy of the block, it's a PITA to make repairs when damage occurs.

**Comment by squeek502** [comment]
Will do. Also planning on adding middle click support for the next version (see #7).
